/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/attachments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["attachments_list"];
        put?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        post: operations["attachments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attachments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["attachments_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        delete: operations["attachments_destroy"];
        options?: never;
        head?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        patch: operations["attachments_partial_update"];
        trace?: never;
    };
    "/api/attachments/{id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["attachments_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attachments/{id}/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        post: operations["attachments_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The global log, limited to domains where the caller holds audit.auditevent:view.
         *     Events with no domain (sign-ins, user changes) are for instance administrators only.
         */
        get: operations["audit_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The global log, limited to domains where the caller holds audit.auditevent:view.
         *     Events with no domain (sign-ins, user changes) are for instance administrators only.
         */
        get: operations["audit_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/trail/{object_type}/{object_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description History of one object, available to anyone who may view that object itself. */
        get: operations["audit_trail_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-fields/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Any signed-in user may read definitions (forms need them); writes follow domain roles. */
        get: operations["custom_fields_list"];
        put?: never;
        /** @description Any signed-in user may read definitions (forms need them); writes follow domain roles. */
        post: operations["custom_fields_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custom-fields/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Any signed-in user may read definitions (forms need them); writes follow domain roles. */
        get: operations["custom_fields_retrieve"];
        /** @description Any signed-in user may read definitions (forms need them); writes follow domain roles. */
        put: operations["custom_fields_update"];
        post?: never;
        /** @description Any signed-in user may read definitions (forms need them); writes follow domain roles. */
        delete: operations["custom_fields_destroy"];
        options?: never;
        head?: never;
        /** @description Any signed-in user may read definitions (forms need them); writes follow domain roles. */
        patch: operations["custom_fields_partial_update"];
        trace?: never;
    };
    "/api/domains/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["domains_list"];
        put?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        post: operations["domains_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["domains_retrieve"];
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        put: operations["domains_update"];
        post?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        delete: operations["domains_destroy"];
        options?: never;
        head?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        patch: operations["domains_partial_update"];
        trace?: never;
    };
    "/api/domains/{id}/effective_permissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["domains_effective_permissions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/tree/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The domains the caller can see, nested. A visible domain whose parent is hidden
         *     becomes a top-level node in that caller's tree.
         */
        get: operations["domains_tree_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/object-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists object types and their actions, so the role editor can offer every permission. */
        get: operations["object_types_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["role_assignments_list"];
        put?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        post: operations["role_assignments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-assignments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["role_assignments_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        delete: operations["role_assignments_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["roles_list"];
        put?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        post: operations["roles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["roles_retrieve"];
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        put: operations["roles_update"];
        post?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        delete: operations["roles_destroy"];
        options?: never;
        head?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        patch: operations["roles_partial_update"];
        trace?: never;
    };
    "/api/user-groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["user_groups_list"];
        put?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        post: operations["user_groups_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-groups/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["user_groups_retrieve"];
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        put: operations["user_groups_update"];
        post?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        delete: operations["user_groups_destroy"];
        options?: never;
        head?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        patch: operations["user_groups_partial_update"];
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["users_list"];
        put?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        get: operations["users_retrieve"];
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        put: operations["users_update"];
        post?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        delete: operations["users_destroy"];
        options?: never;
        head?: never;
        /**
         * @description A model viewset whose rows and writes follow the user's domain-scoped roles.
         *
         *     Subclasses set `object_type` (registry key) and may set `domain_lookup`, the ORM path from
         *     the model to its domain. Set it to None for objects that live outside any domain.
         */
        patch: operations["users_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `create` - Create
         *     * `update` - Update
         *     * `delete` - Delete
         *     * `login` - Login
         *     * `logout` - Logout
         *     * `login_failed` - Login Failed
         *     * `access` - Access
         *     * `other` - Other
         * @enum {string}
         */
        ActionEnum: "create" | "update" | "delete" | "login" | "logout" | "login_failed" | "access" | "other";
        Attachment: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            domain: string;
            /** Format: uri */
            file: string;
            readonly original_name: string;
            readonly content_type: string;
            readonly size: number;
            readonly sha256: string;
            description?: string;
            linked_object_type?: string;
            linked_object_id?: string;
            /** Format: uuid */
            readonly uploaded_by: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        AuditEvent: {
            readonly id: number;
            /** Format: date-time */
            readonly timestamp: string;
            readonly actor_id: string;
            readonly actor_email: string;
            readonly ip_address: string | null;
            readonly action: components["schemas"]["ActionEnum"];
            readonly object_type: string;
            readonly object_id: string;
            readonly object_repr: string;
            readonly domain_id: string;
            readonly changes: {
                [key: string]: unknown;
            };
            readonly prev_hash: string;
            readonly hash: string;
        };
        Csrf: {
            csrfToken: string;
        };
        CustomFieldDefinition: {
            /** Format: uuid */
            readonly id: string;
            object_type: string;
            key: string;
            label: string;
            help_text?: string;
            field_type: components["schemas"]["FieldTypeEnum"];
            required?: boolean;
            choices?: string[];
            /** Format: uuid */
            domain?: string | null;
            /** Format: int64 */
            order?: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Validates the `custom_fields` payload against the definitions that apply to the object.
         *
         *     Subclasses implement `custom_fields_domain(attrs)`, returning the Domain the object will
         *     live in, so the right scoped definitions are used.
         */
        Domain: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
            kind?: components["schemas"]["KindEnum"];
            /** Format: uuid */
            parent?: string | null;
            readonly path: string;
            readonly depth: number;
            custom_fields?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `text` - Text
         *     * `number` - Number
         *     * `boolean` - Yes or no
         *     * `date` - Date
         *     * `choice` - Single choice
         *     * `multi_choice` - Multiple choice
         * @enum {string}
         */
        FieldTypeEnum: "text" | "number" | "boolean" | "date" | "choice" | "multi_choice";
        Grant: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            role: string;
            readonly role_name: string;
            /** Format: uuid */
            domain: string;
            readonly domain_name: string;
            recursive?: boolean;
        };
        /**
         * @description * `organisation` - Organisation
         *     * `subsidiary` - Subsidiary
         *     * `business_unit` - Business unit
         *     * `entity` - Entity
         *     * `team` - Team
         *     * `other` - Other
         * @enum {string}
         */
        KindEnum: "organisation" | "subsidiary" | "business_unit" | "entity" | "team" | "other";
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResult: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            is_superuser: boolean;
            grants: components["schemas"]["Grant"][];
            csrfToken: string;
        };
        Me: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            is_superuser?: boolean;
            readonly grants: components["schemas"]["Grant"][];
        };
        ObjectType: {
            key: string;
            label: string;
            actions: string[];
            supports_custom_fields: boolean;
        };
        PaginatedAttachmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Attachment"][];
        };
        PaginatedAuditEventList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AuditEvent"][];
        };
        PaginatedCustomFieldDefinitionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CustomFieldDefinition"][];
        };
        PaginatedDomainList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Domain"][];
        };
        PaginatedRoleAssignmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RoleAssignment"][];
        };
        PaginatedRoleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Role"][];
        };
        PaginatedUserGroupList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UserGroup"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        Password: {
            current_password: string;
            new_password: string;
        };
        PatchedAttachment: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            domain?: string;
            /** Format: uri */
            file?: string;
            readonly original_name?: string;
            readonly content_type?: string;
            readonly size?: number;
            readonly sha256?: string;
            description?: string;
            linked_object_type?: string;
            linked_object_id?: string;
            /** Format: uuid */
            readonly uploaded_by?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedCustomFieldDefinition: {
            /** Format: uuid */
            readonly id?: string;
            object_type?: string;
            key?: string;
            label?: string;
            help_text?: string;
            field_type?: components["schemas"]["FieldTypeEnum"];
            required?: boolean;
            choices?: string[];
            /** Format: uuid */
            domain?: string | null;
            /** Format: int64 */
            order?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description Validates the `custom_fields` payload against the definitions that apply to the object.
         *
         *     Subclasses implement `custom_fields_domain(attrs)`, returning the Domain the object will
         *     live in, so the right scoped definitions are used.
         */
        PatchedDomain: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            description?: string;
            kind?: components["schemas"]["KindEnum"];
            /** Format: uuid */
            parent?: string | null;
            readonly path?: string;
            readonly depth?: number;
            custom_fields?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedRole: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            description?: string;
            permissions?: string[];
            readonly builtin?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedUser: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: email */
            email?: string;
            first_name?: string;
            last_name?: string;
            is_active?: boolean;
            is_superuser?: boolean;
            password?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedUserGroup: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            description?: string;
            members?: string[];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        Role: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
            permissions?: string[];
            readonly builtin: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        RoleAssignment: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            user?: string | null;
            readonly user_email: string;
            /** Format: uuid */
            group?: string | null;
            readonly group_name: string;
            /** Format: uuid */
            role: string;
            readonly role_name: string;
            /** Format: uuid */
            domain: string;
            readonly domain_name: string;
            recursive?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            is_active?: boolean;
            is_superuser?: boolean;
            password?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        UserGroup: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
            members?: string[];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attachments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttachmentList"];
                };
            };
        };
    };
    attachments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Attachment"];
                "application/x-www-form-urlencoded": components["schemas"]["Attachment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    attachments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    attachments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attachments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedAttachment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAttachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    attachments_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    attachments_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Attachment"];
                "application/x-www-form-urlencoded": components["schemas"]["Attachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    audit_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditEventList"];
                };
            };
        };
    };
    audit_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this audit event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"];
                };
            };
        };
    };
    audit_trail_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
                object_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
        };
    };
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Password"];
                "application/x-www-form-urlencoded": components["schemas"]["Password"];
                "multipart/form-data": components["schemas"]["Password"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    custom_fields_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomFieldDefinitionList"];
                };
            };
        };
    };
    custom_fields_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomFieldDefinition"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomFieldDefinition"];
                "multipart/form-data": components["schemas"]["CustomFieldDefinition"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinition"];
                };
            };
        };
    };
    custom_fields_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this custom field definition. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinition"];
                };
            };
        };
    };
    custom_fields_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this custom field definition. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomFieldDefinition"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomFieldDefinition"];
                "multipart/form-data": components["schemas"]["CustomFieldDefinition"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinition"];
                };
            };
        };
    };
    custom_fields_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this custom field definition. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    custom_fields_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this custom field definition. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomFieldDefinition"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomFieldDefinition"];
                "multipart/form-data": components["schemas"]["PatchedCustomFieldDefinition"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomFieldDefinition"];
                };
            };
        };
    };
    domains_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDomainList"];
                };
            };
        };
    };
    domains_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Domain"];
                "application/x-www-form-urlencoded": components["schemas"]["Domain"];
                "multipart/form-data": components["schemas"]["Domain"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
        };
    };
    domains_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this domain. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
        };
    };
    domains_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this domain. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Domain"];
                "application/x-www-form-urlencoded": components["schemas"]["Domain"];
                "multipart/form-data": components["schemas"]["Domain"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
        };
    };
    domains_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this domain. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    domains_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this domain. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDomain"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDomain"];
                "multipart/form-data": components["schemas"]["PatchedDomain"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
        };
    };
    domains_effective_permissions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this domain. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
        };
    };
    domains_tree_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
        };
    };
    object_types_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectType"][];
                };
            };
        };
    };
    role_assignments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRoleAssignmentList"];
                };
            };
        };
    };
    role_assignments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignment"];
                "application/x-www-form-urlencoded": components["schemas"]["RoleAssignment"];
                "multipart/form-data": components["schemas"]["RoleAssignment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
        };
    };
    role_assignments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this role assignment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
        };
    };
    role_assignments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this role assignment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    roles_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRoleList"];
                };
            };
        };
    };
    roles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Role"];
                "application/x-www-form-urlencoded": components["schemas"]["Role"];
                "multipart/form-data": components["schemas"]["Role"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    roles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    roles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Role"];
                "application/x-www-form-urlencoded": components["schemas"]["Role"];
                "multipart/form-data": components["schemas"]["Role"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    roles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    roles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRole"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRole"];
                "multipart/form-data": components["schemas"]["PatchedRole"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    user_groups_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserGroupList"];
                };
            };
        };
    };
    user_groups_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["UserGroup"];
                "multipart/form-data": components["schemas"]["UserGroup"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
        };
    };
    user_groups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
        };
    };
    user_groups_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["UserGroup"];
                "multipart/form-data": components["schemas"]["UserGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
        };
    };
    user_groups_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_groups_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserGroup"];
                "multipart/form-data": components["schemas"]["PatchedUserGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
