# Generated by Django 6.1.2 on 2026-10-09 05:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=300)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("provider", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("locked", models.BooleanField(default=False)),
                ("redistributable", models.BooleanField(default=True)),
                ("licence_note", models.TextField(blank=True)),
                ("attribution", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=300)),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivatives",
                        to="frameworks.framework",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="frameworks",
                        to="domains.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "version"],
            },
        ),
        migrations.CreateModel(
            name="RequirementNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ref_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("assessable", models.BooleanField(default=True)),
                ("weight", models.PositiveSmallIntegerField(default=1)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="frameworks.framework",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="frameworks.requirementnode",
                    ),
                ),
            ],
            options={
                "ordering": ["framework", "order"],
            },
        ),
        migrations.CreateModel(
            name="RequirementMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("subset", "Subset of"),
                            ("superset", "Superset of"),
                            ("intersects", "Intersects with"),
                            ("related", "Related"),
                        ],
                        default="related",
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings_out",
                        to="frameworks.requirementnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings_in",
                        to="frameworks.requirementnode",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="framework",
            constraint=models.UniqueConstraint(
                fields=("slug", "domain"), name="framework_unique_slug_per_domain"
            ),
        ),
        migrations.AddConstraint(
            model_name="framework",
            constraint=models.UniqueConstraint(
                condition=models.Q(("domain__isnull", True)),
                fields=("slug",),
                name="framework_unique_global_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementnode",
            constraint=models.UniqueConstraint(
                fields=("framework", "ref_id"), name="node_unique_ref_per_framework"
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementmapping",
            constraint=models.UniqueConstraint(
                fields=("source", "target"), name="mapping_unique_pair"
            ),
        ),
    ]
