# Generated by Django 6.1.2 on 2026-10-09 05:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("controls", "0001_initial"),
        ("domains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("probability", models.JSONField(default=list)),
                ("impact", models.JSONField(default=list)),
                ("levels", models.JSONField(default=list)),
                ("grid", models.JSONField(default=list)),
                ("builtin", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("in_review", "In review"),
                            ("done", "Done"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                ("eta", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_assessments",
                        to="domains.domain",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="risk.riskmatrix",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RiskScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("ref_id", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("threats", models.TextField(blank=True)),
                ("vulnerabilities", models.TextField(blank=True)),
                ("existing_controls", models.TextField(blank=True)),
                (
                    "current_probability",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "current_impact",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "residual_probability",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "residual_impact",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("open", "Not decided"),
                            ("mitigate", "Mitigate"),
                            ("accept", "Accept"),
                            ("avoid", "Avoid"),
                            ("transfer", "Transfer"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("justification", models.TextField(blank=True)),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="risk_scenarios",
                        to="controls.appliedcontrol",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True, related_name="risk_scenarios", to="assets.asset"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="risk.riskassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["ref_id", "name"],
            },
        ),
    ]
