# Generated by Django 6.1.2 on 2026-10-08 14:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.attachments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(max_length=300, upload_to=apps.attachments.models.upload_path),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=150)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("linked_object_type", models.CharField(blank=True, max_length=100)),
                ("linked_object_id", models.CharField(blank=True, max_length=64)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="domains.domain",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["linked_object_type", "linked_object_id"],
                        name="attachments_linked__e5bb77_idx",
                    )
                ],
            },
        ),
    ]
