# Generated by Django 6.1.2 on 2026-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "actor_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("access", "Access"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("object_repr", models.CharField(blank=True, max_length=300)),
                (
                    "domain_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id", "-id"],
                        name="audit_audit_object__21569b_idx",
                    )
                ],
            },
        ),
    ]
