# Generated by Django 6.1.2 on 2026-10-09 05:38

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To do"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="to_do",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "Does not repeat"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "recurrence_interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(60)],
                    ),
                ),
                (
                    "last_reminded_on",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("linked_object_type", models.CharField(blank=True, max_length=100)),
                ("linked_object_id", models.CharField(blank=True, max_length=64)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="domains.domain",
                    ),
                ),
                (
                    "next_task",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "priority", "title"],
                "indexes": [
                    models.Index(
                        fields=["assignee", "status", "due_date"],
                        name="tasks_task_assigne_051c4c_idx",
                    ),
                    models.Index(
                        fields=["linked_object_type", "linked_object_id"],
                        name="tasks_task_linked__047fac_idx",
                    ),
                ],
            },
        ),
    ]
