# Generated by Django 6.1.2 on 2026-10-08 14:16

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_type", models.CharField(max_length=100)),
                (
                    "key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]{0,63}$",
                                "Use lower-case letters, digits and underscores, starting with a letter.",
                            )
                        ],
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("help_text", models.CharField(blank=True, max_length=300)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Yes or no"),
                            ("date", "Date"),
                            ("choice", "Single choice"),
                            ("multi_choice", "Multiple choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="domains.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["object_type", "order", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("object_type", "key", "domain"),
                        name="customfield_unique_scoped",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("domain__isnull", True)),
                        fields=("object_type", "key"),
                        name="customfield_unique_global",
                    ),
                ],
            },
        ),
    ]
