# Generated by Django 6.1.2 on 2026-10-09 05:36

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attachments", "0001_initial"),
        ("domains", "0001_initial"),
        ("frameworks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=200)),
                ("ref_id", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To do"),
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("active", "Active"),
                            ("on_hold", "On hold"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="to_do",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("policy", "Policy"),
                            ("process", "Process"),
                            ("technical", "Technical"),
                            ("physical", "Physical"),
                            ("procedure", "Procedure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("xs", "Extra small"),
                            ("s", "Small"),
                            ("m", "Medium"),
                            ("l", "Large"),
                            ("xl", "Extra large"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "control_impact",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("eta", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_controls",
                        to="domains.domain",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="frameworks.requirementnode",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evidence",
                        to="controls.appliedcontrol",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="domains.domain",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "evidence",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="appliedcontrol",
            index=models.Index(fields=["domain", "status"], name="controls_ap_domain__61a8cf_idx"),
        ),
    ]
