# Generated by Django 6.1.2 on 2026-10-08 14:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("organisation", "Organisation"),
                            ("subsidiary", "Subsidiary"),
                            ("business_unit", "Business unit"),
                            ("entity", "Entity"),
                            ("team", "Team"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "path",
                    models.CharField(db_index=True, default="", editable=False, max_length=512),
                ),
                ("depth", models.PositiveSmallIntegerField(default=0, editable=False)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="domains.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "name"), name="domain_unique_name_per_parent"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("parent__isnull", True)),
                        fields=("name",),
                        name="domain_unique_root_name",
                    ),
                ],
            },
        ),
    ]
